/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g431xx.h"
#include <stdint.h>
#include <stdio.h>


#define LED_Pin        0U
#define LED_GPIO_Port  GPIOA

int main(void)
{
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
    LED_GPIO_Port->MODER &= ~(3U << 0);
    LED_GPIO_Port->MODER |=  (1U << 0);

    /* Loop forever */
    
	while (1)
    {
        LED_GPIO_Port->ODR ^= (1U << 0);
        for (volatile uint32_t i = 0; i < 500000; i++);
    }
}
